name: Check version CI

on:
  push:
    tags:
      - '*'

jobs:
  call:
    name: Call check version CI
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/check-version-reusable.yml@main
    with:
      run-tests: true
