name: Cmake CI

on:
#  push:
#    branches:
#      - '**'
#  pull_request:
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  call:
    name: Call Cmake CI
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/cmake-reusable.yml@main
    with:
      run-tests: true
