name: Spack CI

on:
  push:
    branches:
      - '**'
  pull_request:
  # Allows you to run this workflow manually
  workflow_dispatch:

jobs:
  call:
    name: Call Experimental Spack CI on push and PR
    uses: LIHPC-Computational-Geometry/lihpccg-ci/.github/workflows/spack-reusable2.yml@main
