name: spack-install-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    name: ${{ matrix.config }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Linux, Windows or Mac. 
    runs-on:  ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # seems to be needed by codecov
        submodules: recursive

    - name: Initialize the dev environment
      run : > 
        chmod +x ./.github/workflows/env_spack.sh; ./.github/workflows/env_spack.sh

    - name: Build and install
      # We create a subdirectory that will stand as our working directory for all 
      # subsequent commands
      run: spack install tkutil
