name: spack-install-ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    name: ${{ matrix.config }}
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Linux, Windows or Mac. 
    runs-on:  ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config: [Release, Debug]
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2 # seems to be needed by codecov
        submodules: recursive

    - name: Initialize the dev environment
      shell: bash
      run : |
        git clone --depth=1 -b releases/latest https://github.com/spack/spack.git
        sed -i 's#"${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"#"${PACKAGE}"#g' spack/etc/spack/defaults/config.yaml
        . ./spack/share/spack/setup-env.sh
        git clone --depth=1 https://github.com/LIHPC-Computational-Geometry/spack_recipes_meshing.git
  
        spack repo add ./spack_recipes_meshing/meshing_repo
        spack repo add ./spack_recipes_meshing/supersede_repo
  
        spack external find cmake
        spack install lcov
        spack install swig

    - name: Build and install
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        . ./spack/share/spack/setup-env.sh 
        spack clean -m
        spack install tkutil
